matrix:
  password: password1234
  room-id: '!media:matrix.org'
  url: https://matrix.org
  username: marrtrix

marrtrix:
  debug: false

quarkus:
  index-dependency:
    kediatr:
      group-id: com.trendyol
      artifact-id: kediatr-quarkus-starter